version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/src/kernels/shard_engine"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      shard-engine-rust:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/src/kernels/knapsack_solver"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      solver-rust:
        patterns:
          - "*"
