version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/src/kernels/shard_engine"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/src/kernels/knapsack_solver"
    schedule:
      interval: "weekly"
